config/routes.rb
Rails.application.routes.draw do
  get '/auth/github/callback', to: 'sessions#create'
  get '/auth',                 to: 'sessions#prepare', as: 'sign_in'
  get '/auth/failure',         to: 'sessions#oauth_failure'
  delete '/auth',              to: 'sessions#destroy', as: 'sign_out'

  if Rails.env.test? || Rails.env.development?
    get '/auth/force/:user_id',     to: 'sessions#force_signin_in_test'
  end

  resources :walls, only: %i(show create) do
    member do
      post :leave
    end
  end

  resources :accounts, only: %i(new create show) do
    resources :invitations, only: %i(index create destroy) do
      collection do
        get :accept
      end
    end
    member do
      post :leave
    end
    resources :users, only: %i(index create destroy)
  end

  namespace :api do
    post  '/wall/upload-requests',       to: 'walls#create_upload_policy'
    post  '/wall/photos',                to: 'walls#create_photo'
    get   '/wall',                       to: 'walls#show'
    put   '/wall/status',                to: 'walls#status',                as: 'wall_update_status'
  end

  root to: 'static#homepage'
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :account,
    inverse_of: :invitations

  validates :email, email: true, presence: true
  validates :invitation_code, presence: true
  validates :account, presence: true

  validates :email, uniqueness: { scope: :account_id }
  validates :invitation_code, uniqueness: true
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :requires_user_within_account!, except: :accept
  responders :location, :flash
  respond_to :html

  def index
    @invitations = current_account.invitations
    @invitation = current_account.invitations.build
  end

  def create
    @invitation = InviteFriend.execute(current_account, permitted_params)
    if @invitation.persisted?
      respond_with @invitation, location: account_invitations_path(current_account)
    else
      @invitations = current_account.invitations
      render :index
    end
  end

  before_action :requires_registered_user!, :requires_account!, only: :accept
  def accept
    @invitation = current_account.invitations
      .find_by_invitation_code!(params[:invitation_code])

    JoinAccount.execute(current_user, current_account)
    @invitation.destroy

    redirect_to current_account, notice: "Welcome! You've successfully joined the wall!"
  rescue TooManyUsersOnWallException => e
    redirect_to root_path, alert: "Too many people! This is wall is full... try again later!"
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy
    respond_with @invitation, location: account_invitations_path(current_account)
  end

  private

  def permitted_params
    params.require(:invitation).permit(:email)
  end
end

app/views/invitations/index.html.slim
- content_for(:title){ "hi guys! I wish you were here!" }
- content_for(:description){ "Invite your friend to your wall" }

= render 'header'

.inner-page
  .wrap

    .invite
      h3.invite__title
        | Invite your mates!

      .invite__form
        = simple_form_for @invitation, url: account_invitations_path, html: { role: 'invite-form' } do |f|
          = f.input :email
          .invite__form__actions
            = f.button :submit, "Send invitation!"

      - if @invitations.all.find_all(&:persisted?).any?
        .invite__pendings
          .formatted-content
            h4.alpha Pending invitations
            table.invite__table
              thead.invite__table__head
                th name
                th actions
              tbody
                - present_collection(@invitations).each do |invitation|
                  - if invitation.persisted?
                    = invitation.box(:tr) do
                      td
                        = invitation.email
                      td.invite__table__actions
                        = link_to "Cancel", account_invitation_path(current_account, invitation), data: { method: 'delete', confirm: 'Do you really want to cancel the invitation?' }, class: 'button--small'

      - else
        h4.beta No invitations present right now... invite someone!


= render 'footer'