config/routes.rb
Rails.application.routes.draw do
  get '/auth/github/callback', to: 'sessions#create'
  get '/auth',                 to: 'sessions#prepare', as: 'sign_in'
  get '/auth/failure',         to: 'sessions#oauth_failure'
  delete '/auth',              to: 'sessions#destroy', as: 'sign_out'

  if Rails.env.test? || Rails.env.development?
    get '/auth/force/:user_id',     to: 'sessions#force_signin_in_test'
  end

  resources :walls, only: %i(show create) do
    member do
      post :leave
    end
  end

  resources :accounts, only: %i(new create show) do
    resources :invitations, only: %i(index create destroy) do
      collection do
        get :accept
      end
    end
    member do
      post :leave
    end
    resources :users, only: %i(index create destroy)
  end

  namespace :api do
    post  '/wall/upload-requests',       to: 'walls#create_upload_policy'
    post  '/wall/photos',                to: 'walls#create_photo'
    get   '/wall',                       to: 'walls#show'
    put   '/wall/status',                to: 'walls#status',                as: 'wall_update_status'
  end

  root to: 'static#homepage'
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  has_many :users,
    inverse_of: :wall,
    dependent: :destroy

  scope :inactive_since, -> (seconds) { joins(users: :last_image).where(["images.created_at < ?", seconds.ago]) }

  has_one :account,
    inverse_of: :wall

  def to_param
    access_code
  end
end

app/controllers/api/walls_controller.rb
module Api
  class WallsController < BaseController
    before_action :require_user_with_wall!

    def create_upload_policy
      path = "#{Rails.env}/demo-#{wall.access_code}/#{SecureRandom.hex}.jpg"
      @apg = AwsPolicyGenerator.execute(path)
      respond_with @apg, status: :ok
    end

    def create_photo
      StorePhoto.execute(valid_user, params[:s3_url])
      respond_with_success code: 'OK'
    rescue StorePhoto::InvalidInputException
      respond_with_error code: 'INVALID_REQUEST'
    end

    def show
      @users = wall.users.active_in_the_last(5.minutes).by_id
      respond_with @users, status: :ok
    end

    def status
      @user = valid_user
      @user.update_attributes(status_message: params[:status_message])
      respond_to do |format|
        format.json { render status: :ok }
      end
    end

    private

    def require_user_with_wall!
      if !valid_user.present? || !valid_user.wall.present?
        respond_with_error code: 'INVALID_REQUEST'
      end
    end

    def valid_user
      api_user || current_user
    end

    def api_user
      @user ||= if (( header_value = request.headers["HTTP_AUTHORIZATION"] ))
                  User.find_by_secret_token(header_value)
                end
    end

    def wall
      @wall ||= valid_user.wall
    end
  end
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  before_action :autogenerate_guest!
  before_action :init_wall, only: %w(show leave)

  def create
    wall = SetupWall.execute(@user)
    redirect_to wall_path(wall), notice: "Welcome to your wall! Next step: share the link with your friends to let them join the wall!"
  rescue UserAlreadyHasAWallException => e
    redirect_to generic_wall_path(e.wall), alert: "Ouch, You're already part of another wall... please leave this wall before creating a new one!"
  end

  def show
    joined = JoinWall.execute(@user, @wall)
    @pusher_channel = PushEvent.channel_name(@wall)

    if joined
      flash.now[:notice] = "Welcome! You've successfully joined the wall!"
    end
  rescue UserAlreadyHasAWallException => e
    redirect_to generic_wall_path(e.wall), alert: "Ouch, You're already part of another wall... please leave this wall before creating a new one!"
  rescue TooManyUsersOnWallException => e
    LeaveWall.execute(@user, @wall)
    redirect_to root_path, alert: "Too many people! This is wall is full... please create a new one!"
  end

  def leave
    LeaveWall.execute(@user, @wall)
    redirect_to root_path, notice: "You successfully left the wall"
  end

  private

  def init_wall
    @wall = Wall.find_by_access_code!(params[:id])
  end

  def autogenerate_guest!
    @user ||= session_manager.generate_and_sign_in_guest
  end
end

app/views/walls/_camera.html.slim
.wall.js-wall data-pusher-channel=@pusher_channel data-user-id=@user.id
  = audio_tag("beep.ogg")
  .wall__brick.js-camera.is-first
    .wall__brick__idle
      span
        i.icon--camera
        | Waiting for your camera&nbsp;:)
    a.wall__brick__shoot.js-shoot href="#"
      i.wall_brick__icon.icon--photo
    video.wall__brick__camera
    .wall__brick__countdown
    .wall__brick__flash

    .wall__brick__messages
      .wall__brick__status.js-my-status-message = @user.status_message

  .js-friends

app/views/walls/_invite.html.slim
.dialog.js-invite-dialog
  .dialog__frame
    .dialog__body
      .formatted-input
        h1.beta Invite your friends!
        p Copy the wall's URL from the browser address bar and send it to anyone you want to join your wall.
        p A wall accepts a limited number of users. Walls are public but are not linked anywhere. Is up to you to give the address to the right guests!

      .space--top-1
        input(type="text" value=wall_url(@wall) disabled)

app/views/walls/_navbar.html.slim
.wall-nav
  .wall-nav__bar
    .or
      .or__item
        = link_to "hi guys!", root_path, class: "sprite--logo is-small"
        input.update-status-control.js-update-status data-guest-status-url=api_wall_update_status_path placeholder='Write your thoughts here ...'
      .or__item
        a.autoshoot-control.js-autoshoot(href="#")
      .or__item

        - if instance.is_a? Wall
          .wall-nav__item
            = link_to "Share to your friends!", wall_path(instance), class: 'js-invite'
          .wall-nav__item
            = link_to "Leave wall", leave_wall_path(instance), data: { method: 'post' }, role: 'leave', class: 'js-leave'

        - elsif instance.is_a? Account
          .wall-nav__item
            = link_to "Invite a friend!", account_invitations_path(instance)
          .wall-nav__item
            = link_to "Leave wall", leave_account_path(instance), data: { method: 'post' }, role: 'leave', class: 'js-leave'

app/views/walls/_tour.html.slim
ol.js-tour.tourbus-legs

  li.help data-orientation="centered" data-width="500"
    .help__image
      .icon--logo-icon
    .help__body
      .formatted-content
        h3.help__body__title Howdy, welcome to the hall of mates!
        p It seems this is your first time in here... give us a few moments to show you how it works!
      .help__actions
        a.button--large.tourbus-next href="javascript:void(0);" Alright, let me see...

  li.help data-el=".js-camera" data-orientation="right" data-width="500"
    .help__image
      .icon--higuy-lennon
    .help__body
      .formatted-content
        h3.help__body__title This is your spot :)
        p Once your webcam is active, your smiley face will be placed here! You can click on it anytime to take a new photo!
      .help__actions
        a.button.tourbus-next href="javascript:void(0);" Great, move on

  li.help data-el=".js-autoshoot" data-orientation="bottom" data-align="center" data-top="20" data-width="450"
    .help__image
      .icon--higuy-lazy
    .help__body
      .formatted-content
        h3.help__body__title Auto-shoot
        p Every 30 seconds you'll be automatically captured by your camera and your mates will see your photo on their walls! Smile and say "hi guys!"
      .help__actions
        a.button.tourbus-next href="javascript:void(0);" Cool!


  li data-el=".js-update-status" data-orientation="bottom" data-width="450" data-arrow="10%"
    .help__image
      .icon--higuy-blink
    .help__body
      .formatted-content
        h3 This your status
        p Just write down what you're thinking, and press Enter to send it to your friends.
      .help__actions
        a.button.tourbus-next href="javascript:void(0);" Go!

  li.help data-el=".js-invite" data-orientation="bottom" data-align="right" data-arrow="90%" data-top="30" data-width="450"
    .help__image
      .icon--higuy-blink
    .help__body
      .formatted-content
        h3.help__body__title Invite your friends!
        p  Send to them the URL of your wall. As soon as they accept your invitation, they will be on board and you'll see them on your wall.
      .help__actions
        a.button.tourbus-next href="javascript:void(0);" Got it

  li.help data-el=".js-leave" data-orientation="bottom" data-align="right" data-arrow="90%" data-top="30" data-width="450"
    .help__image
      .icon--higuy-gentleman
    .help__body
      .formatted-content
        h3.help__body__title One wall at a time...
        p You can create a new wall or move to an existing one! Keep in mind that you can be present on only one wall at a time and need to leave the existing one before moving.
      .help__actions
        a.button.tourbus-next href="javascript:void(0);" I will do it

  li.help data-el=".wall-nav" data-orientation="bottom" data-align="center" data-top="-40" data-width="450"
    .help__image
      .icon--camera
    .help__body
      .formatted-content
        h3.help__body__title One last, super-important thing!
        p No camera, no picture! Click the "allow" button to let us use your webcam. Then, strike a pose!
      .help__actions
        a.button.tourbus-next href="javascript:void(0);" Understood!

app/views/walls/show.html.slim
.wall-container
  = render "navbar", instance: @wall
  = render "camera"

= render "invite"
= render "tour"

- content_for(:javascript) do
  = javascript_include_tag "//js.pusher.com/2.2/pusher.min.js"