config/routes.rb
Rails.application.routes.draw do
  get '/auth/github/callback', to: 'sessions#create'
  get '/auth',                 to: 'sessions#prepare', as: 'sign_in'
  get '/auth/failure',         to: 'sessions#oauth_failure'
  delete '/auth',              to: 'sessions#destroy', as: 'sign_out'

  if Rails.env.test? || Rails.env.development?
    get '/auth/force/:user_id',     to: 'sessions#force_signin_in_test'
  end

  resources :walls, only: %i(show create) do
    member do
      post :leave
    end
  end

  resources :accounts, only: %i(new create show) do
    resources :invitations, only: %i(index create destroy) do
      collection do
        get :accept
      end
    end
    member do
      post :leave
    end
    resources :users, only: %i(index create destroy)
  end

  namespace :api do
    post  '/wall/upload-requests',       to: 'walls#create_upload_policy'
    post  '/wall/photos',                to: 'walls#create_photo'
    get   '/wall',                       to: 'walls#show'
    put   '/wall/status',                to: 'walls#status',                as: 'wall_update_status'
  end

  root to: 'static#homepage'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def session_manager
    @session_manager ||= SessionManager.new(session)
  end

  delegate :current_user, to: :session_manager
  helper_method :current_user

  def requires_registered_user!
    unless current_user.is_a? RegisteredUser
      session[:redirect_after_auth] = request.fullpath
      redirect_to sign_in_path, alert: 'To access the page you first have to sign in!'
    end
  end

  def requires_user_within_account!
    requires_account!

    if !current_user.wall || current_user.wall.account != current_account
      redirect_to root_path, alert: 'You tried!'
    end
  end

  def requires_account!
    current_account or raise ActiveRecord::RecordNotFound
  end

  def current_account
    @current_account ||= Account.find_by_slug(params[:account_id])
  end
  helper_method :current_account

  def generic_wall_path(wall)
    if wall.account
      account_path(wall.account)
    else
      wall_path(wall)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.slim
- if Rails.env.production?
  javascript:
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("#{ ENV.fetch('SEGMENT_IO_KEY') }");
    window.analytics.page();

app/views/application/_flashes.html.slim
- if flash.any?
  - flash.each do |key, value|
    div(class="flash--#{key}")= value

app/views/application/_footer.html.slim
.footer
  .wrap--on-small-desk
    = link_to "http://www.leanpanda.com", class: "footer__logo", target: "_blank" do
      = image_tag "leanpanda-logo.svg"

    .footer__body
      p hi guys! is a 48h app, passionately made by <a href="http://www.leanpanda.com" target="_blank">Leanpanda Team</a> for the <a href="http://railsrumble.com/entries/66-hi-guys">#railsrumble — 2014 edition</a>
      p Special thanks to <a href="http://www.cantierecreativo.net" target="_blank">Cantiere Creativo</a> and our very understanding families for their support with hosting & free food/bbq!

app/views/application/_head.html.slim
meta charset="utf-8"
meta name="ROBOTS" content="NOODP"
meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,minimal-ui" name="viewport"
title = content_for?(:title) ? yield(:title) : "hi guys!"
meta name="description" content='#{content_for?(:description) ? yield(:description) : "Hi Guys! is a remote presence tool where you can see your colleagues during the working day!"}'

link rel="canonical" href="http://higuys.io#{request.fullpath}"

/ OPEN GRAPH STUFF
meta property="og:title" content="#{yield(:title)}"
meta property="og:type" content="website"
meta property="og:url" content="http://#{request.host+request.fullpath}"
meta property="og:image" content='#{content_for?(:ogimage) ? yield(:ogimage) : image_path("higuys-og-logo.png")}'

meta property="og:site_name" content="hi guys! remote presence tool for the win!"
meta property="og:description" content="#{yield(:description)}"


= stylesheet_link_tag :application, media: "all"
= javascript_include_tag "modernizr"
= csrf_meta_tags

app/views/application/_header.html.slim
.header.js-headroom
  .wrap: .header__inner
    .header__logo
      a.sprite--logo(href=root_path) hi guys!

    .header__menu
      .nav
        - if current_user.present?
          .nav__item
            ' You're signed in as:
            = present(current_user).display_name
          - if current_user.wall
             - if current_user.wall.account
                .nav__item= link_to current_user.wall.account.name, account_path(current_user.wall.account.slug), class: 'button--rev', role: 'goto-wall'
             - else
                .nav__item= link_to "back to demo", wall_path(current_user.wall), class: 'button--rev', role: 'goto-wall'
          - else
            .nav__item= link_to "Make your private wall!", new_account_path, class: 'button--rev', role: 'register-account'
            .nav__item= link_to "Live demo!", walls_path, data: { method: 'post' }, class: 'button--rev', role: 'join-demo-wall'

          .nav__item= link_to "Sign out", sign_out_path, class: 'button--rev', data: { method: 'delete' }, role: 'sign-out'

        - else
          .nav__item= link_to "Sign in", sign_in_path, role: 'sign-in'
          .nav__item= link_to "Make your account", new_account_path, role: 'register-account'
          .nav__item= link_to "Live demo!", walls_path, data: { method: 'post' }, class: 'button--rev header__menu__live-demo', role: 'join-demo-wall'

app/views/application/_javascript.html.slim
= javascript_include_tag :application
= yield :javascript
= render "analytics"

- if Rails.env.test?
  javascript:
    $.fx.off = true;
    $.ajaxSetup({ async: false });

- if Rails.env.production?
  javascript:
    UserVoice=window.UserVoice||[];(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/xnFFTGKxKsB9GLSq3g9Qvw.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})();
    UserVoice.push(['set', { accent_color: '#e23a39', trigger_color: 'white', trigger_background_color: 'rgba(46, 49, 51, 0.6)' }]);
    UserVoice.push(['addTrigger', { mode: 'contact', trigger_position: 'bottom-right' }]);
    UserVoice.push(['autoprompt', {}]);

app/views/application/_ribbon.html.slim
=link_to "http://railsrumble.com/?view=http://leanpanda.r14.railsrumble.com/", class: "ribbon", target: "_blank" do

  .ribbon__logo
    = image_tag "railsrumble-logo.png"

  .ribbon__claim
    p App made in 48h!
    p Vote this project!

  .ribbon__opener
    .sprite--guy-gray